# 开发环境配置 - 热重载优化
spring:
  devtools:
    restart:
      # 启用热重载
      enabled: true
      # 排除不需要重启的目录
      exclude: static/**,public/**
      # 监听额外的路径
      additional-paths: src/main/java
      # 触发重启的文件扩展名
      trigger-file: .reloadtrigger
    livereload:
      # 启用LiveReload（可选，用于浏览器自动刷新）
      enabled: true
      port: 35729
    add-properties: true
  
  # 日志配置
  logging:
    level:
      com.invoice: DEBUG
      org.springframework.boot.devtools: INFO
      
  # JPA配置 - 开发环境
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# 开发环境特定配置
management:
  endpoints:
    web:
      exposure:
        include: health, info, restart